export interface TurkeyCity {
  id: number;
  name: string;
  districts: string[];
}

export const TURKEY_CITIES: TurkeyCity[] = [
  { id: 1, name: 'Adana', districts: ['Seyhan', 'Yüreğir', 'Çukurova', 'Sarıçam', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Karataş', 'Karaisalı', 'Pozantı', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Aladağ'] },
  { id: 2, name: 'Adıyaman', districts: ['Merkez', 'Besni', 'Kahta', 'Gölbaşı', 'Gerger', 'Sincik', 'Tut', 'Samsat', 'Çelikhan'] },
  { id: 3, name: 'Afyonkarahisar', districts: ['Merkez', 'Sandıklı', 'Dinar', 'Bolvadin', 'Emirdağ', 'Şuhut', 'Çay', 'İscehisar', 'Sinanpaşa'] },
  { id: 4, name: 'Ağrı', districts: ['Merkez', 'Doğubayazıt', 'Patnos', 'Eleşkirt', 'Tutak', 'Diyadin', 'Taşlıçay', 'Hamur'] },
  { id: 5, name: 'Amasya', districts: ['Merkez', 'Merzifon', 'Suluova', 'Taşova', 'Gümüşhacıköy', 'Göynücek', 'Hamamözü'] },
  { id: 6, name: 'Ankara', districts: ['Çankaya', 'Yenimahalle', 'Keçiören', 'Etimesgut', 'Mamak', 'Sincan', 'Gölbaşı', 'Altındağ', 'Pursaklar', 'Polatlı', 'Çubuk', 'Kahramankazan', 'Beypazarı', 'Elmadağ', 'Haymana'] },
  { id: 7, name: 'Antalya', districts: ['Muratpaşa', 'Konyaaltı', 'Kepez', 'Alanya', 'Manavgat', 'Serik', 'Kemer', 'Kaş', 'Kumluca', 'Finike', 'Gazipaşa', 'Elmalı', 'Korkuteli', 'Döşemealtı'] },
  { id: 8, name: 'Artvin', districts: ['Merkez', 'Hopa', 'Borçka', 'Arhavi', 'Şavşat', 'Yusufeli', 'Ardanuç', 'Murgul'] },
  { id: 9, name: 'Aydın', districts: ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'İncirliova', 'Germencik', 'Çine', 'Bozdoğan', 'Köşk'] },
  { id: 10, name: 'Balıkesir', districts: ['Karesi', 'Altıeylül', 'Bandırma', 'Edremit', 'Gönen', 'Ayvalık', 'Burhaniye', 'Bigadiç', 'Susurluk', 'Dursunbey', 'Erdek'] },
  { id: 11, name: 'Bilecik', districts: ['Merkez', 'Bozüyük', 'Osmaneli', 'Söğüt', 'Gölpazarı', 'Pazaryeri', 'Yenipazar', 'İnhisar'] },
  { id: 12, name: 'Bingöl', districts: ['Merkez', 'Genç', 'Solhan', 'Karlıova', 'Adaklı', 'Kiğı', 'Yedisu', 'Yayladere'] },
  { id: 13, name: 'Bitlis', districts: ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak', 'Hizan', 'Mutki', 'Adilcevaz'] },
  { id: 14, name: 'Bolu', districts: ['Merkez', 'Gerede', 'Mudurnu', 'Göynük', 'Mengen', 'Yeniçağa', 'Dörtdivan', 'Seben', 'Kıbrıscık'] },
  { id: 15, name: 'Burdur', districts: ['Merkez', 'Bucak', 'Gölhisar', 'Yeşilova', 'Çavdır', 'Tefenni', 'Ağlasun', 'Karamanlı'] },
  { id: 16, name: 'Bursa', districts: ['Nilüfer', 'Osmangazi', 'Yıldırım', 'İnegöl', 'Gemlik', 'Mudanya', 'Mustafakemalpaşa', 'Orhangazi', 'Karacabey', 'Gürsu', 'Kestel', 'Yenişehir'] },
  { id: 17, name: 'Çanakkale', districts: ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Yenice', 'Ezine', 'Bayramiç', 'Ayvacık', 'Lapseki', 'Eceabat', 'Bozcaada', 'Gökçeada'] },
  { id: 18, name: 'Çankırı', districts: ['Merkez', 'Çerkeş', 'Ilgaz', 'Kurşunlu', 'Orta', 'Şabanözü', 'Yapraklı', 'Atkaracalar'] },
  { id: 19, name: 'Çorum', districts: ['Merkez', 'Sungurlu', 'Osmancık', 'İskilip', 'Alaca', 'Bayat', 'Kargı', 'Mecitözü', 'Uğurludağ'] },
  { id: 20, name: 'Denizli', districts: ['Pamukkale', 'Merkezefendi', 'Çivril', 'Acıpayam', 'Tavas', 'Honaz', 'Sarayköy', 'Buldan', 'Kale', 'Çal'] },
  { id: 21, name: 'Diyarbakır', districts: ['Kayapınar', 'Bağlar', 'Yenişehir', 'Sur', 'Ergani', 'Bismil', 'Silvan', 'Çermik', 'Çınar', 'Dicle'] },
  { id: 22, name: 'Edirne', districts: ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala', 'Havsa', 'Meriç', 'Enez', 'Süloğlu', 'Lalapaşa'] },
  { id: 23, name: 'Elazığ', districts: ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu', 'Arıcak', 'Baskil', 'Maden', 'Sivrice', 'Keban'] },
  { id: 24, name: 'Erzincan', districts: ['Merkez', 'Tercan', 'Üzümlü', 'Refahiye', 'Çayırlı', 'Ilıç', 'Kemah', 'Kemaliye'] },
  { id: 25, name: 'Erzurum', districts: ['Yakutiye', 'Palandöken', 'Aziziye', 'Horasan', 'Oltu', 'Pasinler', 'Karayazı', 'Hınıs', 'Tekman'] },
  { id: 26, name: 'Eskişehir', districts: ['Odunpazarı', 'Tepebaşı', 'Sivrihisar', 'Çifteler', 'Seyitgazi', 'Alpu', 'Mahmudiye', 'İnönü'] },
  { id: 27, name: 'Gaziantep', districts: ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Araban', 'Yavuzeli', 'Karkamış'] },
  { id: 28, name: 'Giresun', districts: ['Merkez', 'Bulancak', 'Espiye', 'Görele', 'Tirebolu', 'Şebinkarahisar', 'Keşap', 'Dereli', 'Yağlıdere'] },
  { id: 29, name: 'Gümüşhane', districts: ['Merkez', 'Kelkit', 'Şiran', 'Kürtün', 'Köse', 'Torul'] },
  { id: 30, name: 'Hakkari', districts: ['Merkez', 'Yüksekova', 'Şemdinli', 'Çukurca', 'Derecik'] },
  { id: 31, name: 'Hatay', districts: ['Antakya', 'İskenderun', 'Defne', 'Dörtyol', 'Samandağ', 'Kırıkhan', 'Reyhanlı', 'Arsuz', 'Payas', 'Altınözü', 'Hassa'] },
  { id: 32, name: 'Isparta', districts: ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Gelendost', 'Senirkent', 'Keçiborlu', 'Uluborlu'] },
  { id: 33, name: 'Mersin', districts: ['Tarsus', 'Toroslar', 'Yenişehir', 'Akdeniz', 'Mezitli', 'Erdemli', 'Silifke', 'Anamur', 'Mut', 'Bozyazı', 'Gülnar'] },
  { id: 34, name: 'İstanbul', districts: ['Kadıköy', 'Ümraniye', 'Beşiktaş', 'Şişli', 'Üsküdar', 'Ataşehir', 'Bakırköy', 'Maltepe', 'Pendik', 'Zeytinburnu', 'Fatih', 'Beyoğlu', 'Beylikdüzü', 'Başakşehir', 'Esenyurt', 'Küçükçekmece', 'Büyükçekmece', 'Kartal', 'Tuzla', 'Sancaktepe', 'Sultanbeyli', 'Çekmeköy', 'Kağıthane', 'Sarıyer', 'Eyüpsultan', 'Gaziosmanpaşa', 'Bayrampaşa', 'Esenler', 'Güngören', 'Bağcılar', 'Bahçelievler', 'Avcılar', 'Silivri', 'Çatalca', 'Şile', 'Adalar'] },
  { id: 35, name: 'İzmir', districts: ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Bayraklı', 'Çiğli', 'Gaziemir', 'Balçova', 'Narlıdere', 'Güzelbahçe', 'Karabağlar', 'Torbalı', 'Menemen', 'Kemalpaşa', 'Aliağa', 'Bergama', 'Ödemiş', 'Tire', 'Urla', 'Çeşme', 'Seferihisar', 'Foça', 'Dikili', 'Menderes'] },
  { id: 36, name: 'Kars', districts: ['Merkez', 'Kağızman', 'Sarıkamış', 'Digor', 'Selim', 'Arpaçay', 'Akyaka', 'Susuz'] },
  { id: 37, name: 'Kastamonu', districts: ['Merkez', 'Tosya', 'Taşköprü', 'Cide', 'İnebolu', 'Araç', 'Devrekani', 'Daday', 'Bozkurt', 'Küre'] },
  { id: 38, name: 'Kayseri', districts: ['Melikgazi', 'Kocasinan', 'Talas', 'Develi', 'Yahyalı', 'Bünyan', 'Pınarbaşı', 'Tomarza', 'Yeşilhisar'] },
  { id: 39, name: 'Kırklareli', districts: ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Pınarhisar', 'Demirköy', 'Kofçaz', 'Pehlivanköy'] },
  { id: 40, name: 'Kırşehir', districts: ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı', 'Akpınar', 'Akçakent', 'Boztepe'] },
  { id: 41, name: 'Kocaeli', districts: ['İzmit', 'Gebze', 'Darıca', 'Körfez', 'Gölcük', 'Derince', 'Çayırova', 'Kartepe', 'Başiskele', 'Karamürsel', 'Kandıra', 'Dilovası'] },
  { id: 42, name: 'Konya', districts: ['Selçuklu', 'Karatay', 'Meram', 'Ereğli', 'Akşehir', 'Beyşehir', 'Çumra', 'Seydişehir', 'Cihanbeyli', 'Kulu', 'Karapınar'] },
  { id: 43, name: 'Kütahya', districts: ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Altıntaş', 'Domaniç', 'Hisarcık', 'Aslanapa'] },
  { id: 44, name: 'Malatya', districts: ['Battalgazi', 'Yeşilyurt', 'Doğanşehir', 'Darende', 'Akçadağ', 'Hekimhan', 'Pütürge', 'Yazıhan', 'Arapgir'] },
  { id: 45, name: 'Manisa', districts: ['Yunusemre', 'Şehzadeler', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma', 'Alaşehir', 'Saruhanlı', 'Kula', 'Demirci', 'Gördes'] },
  { id: 46, name: 'Kahramanmaraş', districts: ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Pazarcık', 'Göksun', 'Türkoğlu', 'Andırın', 'Çağlayancerit'] },
  { id: 47, name: 'Mardin', districts: ['Artuklu', 'Kızıltepe', 'Nusaybin', 'Midyat', 'Derik', 'Mazıdağı', 'Dargeçit', 'Savur', 'Ömerli'] },
  { id: 48, name: 'Muğla', districts: ['Bodrum', 'Fethiye', 'Marmaris', 'Menteşe', 'Milas', 'Ortaca', 'Dalaman', 'Yatağan', 'Seydikemer', 'Datça', 'Ula'] },
  { id: 49, name: 'Muş', districts: ['Merkez', 'Bulanık', 'Malazgirt', 'Varto', 'Hasköy', 'Korkut'] },
  { id: 50, name: 'Nevşehir', districts: ['Merkez', 'Ürgüp', 'Avanos', 'Gülşehir', 'Derinkuyu', 'Kozaklı', 'Acıgöl', 'Hacıbektaş'] },
  { id: 51, name: 'Niğde', districts: ['Merkez', 'Bor', 'Çiftlik', 'Ulukışla', 'Altunhisar', 'Çamardı'] },
  { id: 52, name: 'Ordu', districts: ['Altınordu', 'Ünye', 'Fatsa', 'Gölköy', 'Perşembe', 'Kumru', 'Korgan', 'Aybastı', 'Ulubey', 'Akkuş'] },
  { id: 53, name: 'Rize', districts: ['Merkez', 'Çayeli', 'Ardeşen', 'Pazar', 'Fındıklı', 'Güneysu', 'Kalkandere', 'İkizdere', 'Derepazarı'] },
  { id: 54, name: 'Sakarya', districts: ['Serdivan', 'Adapazarı', 'Erenler', 'Hendek', 'Akyazı', 'Karasu', 'Geyve', 'Sapanca', 'Pamukova', 'Ferizli', 'Kocaali'] },
  { id: 55, name: 'Samsun', districts: ['Atakum', 'İlkadım', 'Canik', 'Bafra', 'Çarşamba', 'Vezirköprü', 'Terme', 'Tekkeköy', 'Havza', 'Alaçam', '19 Mayıs'] },
  { id: 56, name: 'Siirt', districts: ['Merkez', 'Kurtalan', 'Eruh', 'Baykan', 'Şirvan', 'Pervari', 'Tillo'] },
  { id: 57, name: 'Sinop', districts: ['Merkez', 'Boyabat', 'Gerze', 'Ayancık', 'Durağan', 'Türkeli', 'Erfelek', 'Dikmen', 'Saraydüzü'] },
  { id: 58, name: 'Sivas', districts: ['Merkez', 'Şarkışla', 'Yıldızeli', 'Suşehri', 'Gemerek', 'Zara', 'Kangal', 'Gürün', 'Divriği', 'Koyulhisar'] },
  { id: 59, name: 'Tekirdağ', districts: ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Kapaklı', 'Ergene', 'Malkara', 'Saray', 'Hayrabolu', 'Muratlı', 'Şarköy', 'Marmaraereğlisi'] },
  { id: 60, name: 'Tokat', districts: ['Merkez', 'Erbaa', 'Turhal', 'Niksar', 'Zile', 'Reşadiye', 'Almus', 'Pazar', 'Yeşilyurt', 'Artova'] },
  { id: 61, name: 'Trabzon', districts: ['Ortahisar', 'Akçaabat', 'Araklı', 'Of', 'Yomra', 'Arsin', 'Vakfıkebir', 'Sürmene', 'Beşikdüzü', 'Çarşıbaşı', 'Maçka'] },
  { id: 62, name: 'Tunceli', districts: ['Merkez', 'Pertek', 'Mazgirt', 'Çemişgezek', 'Hozat', 'Ovacık', 'Pülümür', 'Nazımiye'] },
  { id: 63, name: 'Şanlıurfa', districts: ['Haliliye', 'Eyyübiye', 'Karaköprü', 'Siverek', 'Viranşehir', 'Suruç', 'Birecik', 'Ceylanpınar', 'Harran', 'Bozova', 'Akçakale', 'Hilvan'] },
  { id: 64, name: 'Uşak', districts: ['Merkez', 'Banaz', 'Eşme', 'Sivaslı', 'Ulubey', 'Karahallı'] },
  { id: 65, name: 'Van', districts: ['Ipekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Özalp', 'Çaldıran', 'Muradiye', 'Gürpınar', 'Başkale', 'Gevaş', 'Çatak'] },
  { id: 66, name: 'Yozgat', districts: ['Merkez', 'Sorgun', 'Akdağmadeni', 'Yerköy', 'Boğazlıyan', 'Sarıkaya', 'Çekerek', 'Şefaatli', 'Saraykent'] },
  { id: 67, name: 'Zonguldak', districts: ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Kozlu', 'Kilimli', 'Alaplı', 'Gökçebey'] },
  { id: 68, name: 'Aksaray', districts: ['Merkez', 'Ortaköy', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Sarıyahşi', 'Sultanhanı'] },
  { id: 69, name: 'Bayburt', districts: ['Merkez', 'Demirözü', 'Aydıntepe'] },
  { id: 70, name: 'Karaman', districts: ['Merkez', 'Ermenek', 'Sarıveliler', 'Kazımkarabekir', 'Başyayla', 'Ayrancı'] },
  { id: 71, name: 'Kırıkkale', districts: ['Merkez', 'Yahşihan', 'Keskin', 'Delice', 'Bahşılı', 'Sulakyurt', 'Balışeyh', 'Karakeçili', 'Çelebi'] },
  { id: 72, name: 'Batman', districts: ['Merkez', 'Kozluk', 'Sason', 'Beşiri', 'Gercüş', 'Hasankeyf'] },
  { id: 73, name: 'Şırnak', districts: ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Uludere', 'Beytüşşebap', 'Güçlükonak'] },
  { id: 74, name: 'Bartın', districts: ['Merkez', 'Ulus', 'Amasra', 'Kurucaşile'] },
  { id: 75, name: 'Ardahan', districts: ['Merkez', 'Göle', 'Çıldır', 'Hanak', 'Posof', 'Damal'] },
  { id: 76, name: 'Iğdır', districts: ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'] },
  { id: 77, name: 'Yalova', districts: ['Merkez', 'Çiftlikköy', 'Çınarcık', 'Altınova', 'Armutlu', 'Termal'] },
  { id: 78, name: 'Karabük', districts: ['Merkez', 'Safranbolu', 'Yenice', 'Eskipazar', 'Eflani', 'Ovacık'] },
  { id: 79, name: 'Kilis', districts: ['Merkez', 'Musabeyli', 'Elbeyli', 'Polateli'] },
  { id: 80, name: 'Osmaniye', districts: ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Toprakkale', 'Sumbas', 'Hasanbeyli'] },
  { id: 81, name: 'Düzce', districts: ['Merkez', 'Akçakoca', 'Kaynaşlı', 'Gölyaka', 'Çilimli', 'Yığılca', 'Gümüşova', 'Cumayeri'] },
];

export const getDistrictsByCityName = (cityName: string): string[] => {
  const city = TURKEY_CITIES.find(c => c.name.toLowerCase() === cityName.toLowerCase());
  return city ? city.districts : ['Merkez'];
};
